remote_theme: nandomoreirame/simplest

# SEO settings
title: "P-RECS'19"
description: "2nd International Workshop on Practical Reproducible Evaluation of Computer Systems"
keywords: "reproducibility, automation, devops, sciops, hpdc"
url: https://p-recs.github.io
baseurl: "/2019"
# baseurl: null

#google_analytics: UA-52446115-1
repo: http://github.com/p-recs/2019
disqus_shortname: ""

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Ivo Jimenez
  job      : PhD Candidate
  bio      : "yeah."
  thumb    : /assets/logo.png
  email    : ivo.jimenez@ucsc.edu
  url      : http://ivotron.me
  github   : http://github.com/ivotron
  twitter  : http://twitter.com/ivotron
  facebook : http://facebook.com/ivotron
  linkedin : http://linkedin.com/in/ivotron

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
