# SEO settings
title: "P-RECS'19"
description: "2nd International Workshop on Practical Reproducible Evaluation of Computer Systems"
keywords: "reproducibility, automation, devops, sciops, hpdc"
url: https://p-recs.github.io
baseurl: "/2019"
# baseurl: null

theme: jekyll-theme-slate
